FROM node:18 AS builder

RUN apt-get update -y && \
    apt-get install -y git g++ python3 build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY /frontend/ .

RUN npm install

RUN ls -la

CMD ["npm", "run", "test:pact"]

FROM golang:1.20

RUN apt-get update

RUN apt-get install curl

WORKDIR /app

RUN curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-linux-x86_64.tar.gz

RUN tar xzf pact-1.91.0-linux-x86_64.tar.gz

RUN rm pact-1.91.0-linux-x86_64.tar.gz

ENV PATH $PATH:/app/pact/bin

ENV CGO_ENABLED=0

COPY /backend .

COPY --from=builder /app/pacts .

CMD ["go", "test", "provider_test.go"]
