version: "3.7"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'todo_app'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3306:3306'
    volumes:
      - ./database/init.ddl:/docker-entrypoint-initdb.d/1-ddl.sql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile

    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"


  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

