name: Build Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Go Build
        working-directory: backend
        run: go build -v ./...

      - name: Go Test
        working-directory: backend
        run: go test -skip TestProvider -v ./...

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm ci
        working-directory: frontend
        run: npm ci

      - name: npm build
        working-directory: frontend
        run: npm run build --if-present

      - name: npm test
        working-directory: frontend
        run: npm run test:unit

  #dockerize:
  #deploy2TestEnv:
  #consumer-driven-contract-tests:
  #ui-acceptance-tests:
  #deploy2Prod:
